### PR TITLE
compatible v-icon

### PR DESCRIPTION
**Pull request by robin-dongbin**
Use Vuetify's way.

### CODE REVIEW

**Comment by eolant** [comment]
Doesn't work for me.

**Comment by robin-dongbin** [comment]
You can read source code of `vuetify`

**Comment by eolant** [comment]
I did, just saying your pull request doesn't work on the demo page. Have you tested it?

**Comment by robin-dongbin** [comment]
Sure,It works well in my case

**Comment by eolant** [comment]
Link?

**Comment by robin-dongbin** [comment]
I only test in my local environment.
There is the `vuetify` source code:
https://github.com/vuetifyjs/vuetify/blob/f329abc3d3f267691753ab6c329070a045fde19f/packages/vuetify/src/util/helpers.ts#L325

**Comment by eolant** [comment]
Cool, but it will not work in the case of this library. Try it yourself, build it and include local index.umd.js in index.html if you haven't tested it properly. I'm closing this pull request and will add an option to specify close icon.

**Pull request closed without merging**
